package com.ds.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUid(java.lang.String uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

	public M setUname(java.lang.String uname) {
		set("uname", uname);
		return (M)this;
	}
	
	public java.lang.String getUname() {
		return getStr("uname");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setMedicalHistory(java.lang.String medicalHistory) {
		set("medical_history", medicalHistory);
		return (M)this;
	}
	
	public java.lang.String getMedicalHistory() {
		return getStr("medical_history");
	}

	public M setSymptom(java.lang.String symptom) {
		set("symptom", symptom);
		return (M)this;
	}
	
	public java.lang.String getSymptom() {
		return getStr("symptom");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setAccount(java.lang.String account) {
		set("account", account);
		return (M)this;
	}
	
	public java.lang.String getAccount() {
		return getStr("account");
	}

	public M setPasswd(java.lang.String passwd) {
		set("passwd", passwd);
		return (M)this;
	}
	
	public java.lang.String getPasswd() {
		return getStr("passwd");
	}

}
